{
 "title": "Microsoft SQL Server Dashboard",
 "description": "This is a comprehensive Microsoft SQL Server Dashboard designed to monitor key performance indicators. It provides real-time insights into your SQL Server environment.",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 2, "x": 0, "y": 1 },
   "options": {
    "content": "\n<div>\n  <img style=\"height: 80%;width: 80%;display: block;margin: auto auto;\" src=\"https://www.svgrepo.com/show/303229/microsoft-sql-server-logo.svg\"/>\n</div>"
   }
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "DemoDB",
     "rawSql": "SELECT DB_NAME() AS DatabaseName;\n"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "date" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "DemoDB",
     "rawSql": "SELECT sqlserver_start_time as 'SQL SERVER START TIME'\nFROM sys.dm_os_sys_info;\n"
    }
   ]
  },
  {
   "title": "Active User Sessions",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 17, "x": 7, "y": 1 },
   "targets": [
    {
     "dataset": "_DBA",
     "rawSql": "SELECT login_name AS LoginName,\n       COUNT(session_id) AS SessionCount\nFROM sys.dm_exec_sessions\nWHERE is_user_process = 1\nGROUP BY login_name\nORDER BY SessionCount DESC;\n"
    }
   ]
  },
  { "title": "Errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Recent Application Exceptions",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "dataset": "EduEgate_2022_Log",
     "rawSql": "SELECT TOP 10 AppId, CreatedDate, ExceptionIID, Message, SerializedException\r\nFROM EduEgate_2022_Log.errors.exceptions\r\nWHERE $__timeFilter([CreatedDate])\r\nORDER BY [CreatedDate] DESC"
    }
   ]
  },
  { "title": "Query Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Top Queries by Resource Consumption",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "dataset": "_DBA",
     "rawSql": "SELECT TOP 10\n    DB_NAME(CONVERT(INT, pa.value)) AS DatabaseName,\n    qs.last_execution_time AS time,\n    qs.execution_count AS ExecCount,\n    qs.total_elapsed_time / qs.execution_count / 1000.0 AS AvgElapsedMs,\n    qs.total_logical_reads / qs.execution_count AS AvgLogicalReads,\n    qs.total_worker_time / qs.execution_count / 1000.0 AS AvgCPUms,\n    SUBSTRING(st.text, (qs.statement_start_offset/2) + 1,\n        ((CASE qs.statement_end_offset\n            WHEN -1 THEN DATALENGTH(st.text)\n            ELSE qs.statement_end_offset\n        END - qs.statement_start_offset)/2) + 1) AS QueryText\nFROM sys.dm_exec_query_stats qs\nCROSS APPLY sys.dm_exec_sql_text(qs.sql_handle) AS st\nCROSS APPLY sys.dm_exec_plan_attributes(qs.plan_handle) AS pa\nWHERE pa.attribute = 'dbid'\nAND qs.last_execution_time BETWEEN\n      $__timeFrom() AND $__timeTo()\nORDER BY qs.last_execution_time DESC;"
    }
   ]
  },
  {
   "title": "Most CPU-Intensive Queries",
   "type": "table",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "dataset": "EduEgate_2022",
     "rawSql": "USE EduEgate_2022\r\nSELECT TOP 10\r\n    qtxt.query_sql_text AS QueryText,\r\n    -- Calculate total CPU time in the interval (avg * count)\r\n    SUM(rs.count_executions * rs.avg_cpu_time) AS CPUTime\r\nFROM \r\n    sys.query_store_query_text AS qtxt\r\nJOIN \r\n    sys.query_store_query AS qry ON qtxt.query_text_id = qry.query_text_id\r\nJOIN \r\n    sys.query_store_plan AS p ON qry.query_id = p.query_id\r\nJOIN \r\n    sys.query_store_runtime_stats AS rs ON p.plan_id = rs.plan_id\r\nJOIN \r\n    sys.query_store_runtime_stats_interval AS rsi ON rs.runtime_stats_interval_id = rsi.runtime_stats_interval_id\r\nWHERE\r\n    -- This is the Grafana macro that applies the dashboard time filter\r\n    $__timeFilter(rsi.start_time)\r\nGROUP BY\r\n    qtxt.query_sql_text\r\nORDER BY\r\n    CPUTime DESC;"
    }
   ]
  },
  {
   "title": "Longest Running Queries (Avg Duration)",
   "type": "table",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "dataset": "BKP_Update_Data",
     "rawSql": "USE EduEgate_2022;\r\n\r\nSELECT TOP 10\r\n    qtxt.query_sql_text AS QueryText,\r\n    -- Calculate the weighted average duration\r\n    -- (Total Duration / Total Executions)\r\n    SUM(rs.avg_duration * rs.count_executions) / SUM(rs.count_executions) AS AvgDuration\r\nFROM \r\n    sys.query_store_query_text AS qtxt\r\nJOIN \r\n    sys.query_store_query AS qry ON qtxt.query_text_id = qry.query_text_id\r\nJOIN \r\n    sys.query_store_plan AS p ON qry.query_id = p.query_id\r\nJOIN \r\n    sys.query_store_runtime_stats AS rs ON p.plan_id = rs.plan_id\r\nJOIN \r\n    sys.query_store_runtime_stats_interval AS rsi ON rs.runtime_stats_interval_id = rsi.runtime_stats_interval_id\r\nWHERE\r\n    -- Grafana macro that applies the dashboard time filter\r\n    $__timeFilter(rsi.start_time)\r\nGROUP BY\r\n    qtxt.query_sql_text\r\n-- Add a HAVING clause to prevent divide-by-zero errors and filter out queries that didn't run\r\nHAVING\r\n    SUM(rs.count_executions) > 0\r\nORDER BY\r\n    -- Order by the highest average duration to find the slowest queries\r\n    AvgDuration DESC;"
    }
   ]
  },
  {
   "title": "Top Queries by CPU Utilization",
   "type": "table",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "dataset": "BKP_Update_Data",
     "rawSql": "SELECT TOP 10\r\n    st.text AS QueryText,\r\n    qs.execution_count,\r\n    -- Average time the CPU was busy\r\n    qs.total_worker_time / qs.execution_count AS AvgCPUTime_us,\r\n    -- Average time from start to finish (wall-clock time) for context\r\n    qs.total_elapsed_time / qs.execution_count AS AvgDuration_us,\r\n    -- Also include total times for context\r\n    qs.last_elapsed_time,\r\n    qs.total_worker_time\r\nFROM \r\n    sys.dm_exec_query_stats qs\r\nCROSS APPLY \r\n    sys.dm_exec_sql_text(qs.sql_handle) st\r\nWHERE \r\n    qs.execution_count > 1 -- Use > 1 to avoid one-off expensive queries if desired\r\nORDER BY \r\n    AvgCPUTime_us DESC; -- Sort by the highest average CPU TIME"
    }
   ]
  },
  {
   "title": "Top Accessed Indexes",
   "type": "table",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "DemoDB",
     "rawSql": "SELECT \n    OBJECT_NAME(s.object_id) AS TableName,\n    i.name AS IndexName,\n    s.user_seeks,\n    s.user_scans\nFROM sys.dm_db_index_usage_stats AS s\nINNER JOIN sys.indexes AS i ON i.object_id = s.object_id AND i.index_id = s.index_id\nWHERE s.database_id = DB_ID('EduEgate_2022')\nORDER BY s.user_seeks DESC;\n"
    }
   ]
  },
  {
   "title": "Query Latency",
   "type": "table",
   "gridPos": { "h": 14, "w": 9, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "dataset": "_DBA",
     "rawSql": "SELECT TOP 10  \nlast_execution_time AS LastExecutedTime,\nlast_elapsed_time/1000 AS LastElapsedTime,\nlast_worker_time/1000 AS LastCPUTime,\n       --creation_time AS CreationTime,\n       --total_elapsed_time/1000 AS TotalElapsedTimeMS,\n      execution_count AS ExecutionCount\n      --total_worker_time/1000 AS CPUTimeMS\nFROM sys.dm_exec_query_stats\nWHERE $__timeFilter(last_execution_time)\nORDER BY LastElapsedTime DESC, LastExecutedTime DESC;\n"
    }
   ]
  },
  {
   "title": "Table Locks",
   "type": "table",
   "gridPos": { "h": 14, "w": 9, "x": 9, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "DemoDB",
     "rawSql": "SELECT \n    request_session_id AS SessionID,\n    resource_database_id AS DatabaseID,\n    resource_associated_entity_id AS EntityID,\n    request_mode AS LockType,\n    request_status AS Status\nFROM sys.dm_tran_locks;\n"
    }
   ]
  },
  {
   "title": "Query Plan Cache Efficiency",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 53 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "_DBA",
     "rawSql": "SELECT cacheobjtype AS CacheObjectType,\n       objtype AS ObjectType,\n       usecounts AS 'Use Count',\n       size_in_bytes AS 'Cache Size'\nFROM sys.dm_exec_cached_plans\nWHERE usecounts < 10;\n"
    }
   ]
  },
  {
   "title": "Current Connections",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 56 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "DemoDB",
     "rawSql": "SELECT COUNT(session_id) AS Connections\nFROM sys.dm_exec_sessions\nWHERE is_user_process = 1;\n"
    }
   ]
  },
  {
   "title": "Database Query Efficiency",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 56 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "DemoDB",
     "rawSql": "SELECT \n    (CAST(SUM(CASE WHEN usecounts > 0 THEN 1 ELSE 0 END) AS FLOAT) / COUNT(*)) * 100 AS Cache_Hit_Ratio\nFROM sys.dm_exec_cached_plans\nWHERE objtype = 'Adhoc'\n    OR objtype = 'Prepared';\n"
    }
   ]
  },
  {
   "title": "Query Execution Statistics",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 61 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "BKP_Update_Data",
     "rawSql": "SELECT\r\n    -- Calculate a weighted average duration for all queries in the time range\r\n    SUM(qs.total_elapsed_time) / SUM(qs.execution_count) / 1000.0 as 'Avg Duration ms',\r\n    -- Sum all execution counts for a total in the time range\r\n    SUM(qs.execution_count) as 'Execution Count'\r\nFROM sys.dm_exec_query_stats AS qs\r\nWHERE $__timeFilter(qs.last_execution_time)"
    }
   ]
  },
  { "title": "Jobs Monitoring", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 } },
  {
   "title": "Job Execution Frequency",
   "type": "bargauge",
   "description": "Last 7 days",
   "gridPos": { "h": 14, "w": 4, "x": 0, "y": 68 },
   "targets": [
    {
     "dataset": "_DBA",
     "rawSql": "SELECT job.name AS JobName,\n       COUNT(run.run_date) AS ExecutionCount\nFROM msdb.dbo.sysjobs AS job\nINNER JOIN msdb.dbo.sysjobhistory AS run\nON job.job_id = run.job_id\nWHERE run.run_date >= CONVERT(VARCHAR, GETDATE() - 7, 112)  -- Last 7 days\nGROUP BY job.name\nORDER BY ExecutionCount DESC\n"
    }
   ]
  },
  {
   "title": "Jobs in progress",
   "type": "table",
   "gridPos": { "h": 3, "w": 8, "x": 4, "y": 68 },
   "targets": [
    {
     "dataset": "_DBA",
     "rawSql": "SELECT DISTINCT \n       job.name AS JobName,\n       activity.run_requested_date AS StartTime,\n       DATEDIFF(SECOND, activity.run_requested_date, GETDATE()) AS RunDurationSeconds\nFROM msdb.dbo.sysjobs AS job\nINNER JOIN msdb.dbo.sysjobactivity AS activity\n    ON job.job_id = activity.job_id\nWHERE activity.run_requested_date IS NOT NULL\n  AND activity.stop_execution_date IS NULL\nORDER BY activity.run_requested_date DESC;\n"
    }
   ]
  },
  {
   "title": "Scheduled and Running Jobs",
   "type": "table",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 68 },
   "targets": [
    {
     "dataset": "_DBA",
     "rawSql": "SELECT TOP 20\n       job.name AS JobName,\n       CASE\n           WHEN activity.run_requested_date IS NULL THEN 'Scheduled'\n           ELSE 'Running'\n       END AS JobStatus,\n       schedule.next_run_date AS NextRunDate,\n       schedule.next_run_time AS NextRunTime\nFROM msdb.dbo.sysjobs AS job\nLEFT JOIN msdb.dbo.sysjobactivity AS activity\n    ON job.job_id = activity.job_id\nLEFT JOIN msdb.dbo.sysjobschedules AS schedule\n    ON job.job_id = schedule.job_id\nWHERE activity.stop_execution_date IS NULL  -- Running jobs\n   OR schedule.next_run_date IS NOT NULL       -- Scheduled jobs\nORDER BY schedule.next_run_date, schedule.next_run_time;\n"
    }
   ]
  },
  {
   "title": "Job Execution History Duration",
   "type": "table",
   "gridPos": { "h": 11, "w": 8, "x": 4, "y": 71 },
   "targets": [
    {
     "dataset": "_DBA",
     "rawSql": "SELECT job.name AS JobName,\n       run.run_date AS RunDate,\n       run.run_duration AS RunDuration\nFROM msdb.dbo.sysjobs AS job\nINNER JOIN msdb.dbo.sysjobhistory AS run\nON job.job_id = run.job_id\nWHERE run.step_id = 0  -- 0 indicates job level information\nORDER BY run.run_date DESC\n"
    }
   ]
  },
  {
   "title": "Server Performance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 82 },
   "collapsed": true,
   "panels": [
    {
     "title": "Active Transactions",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 83 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "dataset": "_DBA",
       "rawSql": "SELECT transaction_id AS TransactionID,\n       transaction_begin_time AS BeginTime,\n       transaction_state AS State,\n       transaction_type AS Type\nFROM sys.dm_tran_active_transactions;\n"
      }
     ]
    },
    {
     "title": "Failed Jobs Overview",
     "type": "table",
     "gridPos": { "h": 17, "w": 16, "x": 8, "y": 83 },
     "targets": [
      {
       "dataset": "_DBA",
       "rawSql": "SELECT job.name AS JobName,\n       run.run_date AS RunDate,\n       run.run_time AS RunTime,\n       run.run_duration AS RunDuration,\n       run.message AS ErrorMessage\nFROM msdb.dbo.sysjobs AS job\nINNER JOIN msdb.dbo.sysjobhistory AS run\nON job.job_id = run.job_id\nWHERE run.run_status = 0  -- 0 indicates failure\nORDER BY run.run_date DESC\n"
      }
     ]
    },
    {
     "title": "Wait Times Monitoring",
     "type": "bargauge",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 89 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "dataset": "_DBA",
       "rawSql": "SELECT wait_type, \n       SUM(wait_time_ms) AS WaitTimeMS, \n       SUM(waiting_tasks_count) AS TaskCount\nFROM sys.dm_os_wait_stats\nWHERE wait_type NOT IN ('SLEEP_TASK', 'BROKER_TASK_STOP', 'SQLTRACE_BUFFER_FLUSH')\nGROUP BY wait_type\nORDER BY WaitTimeMS DESC;\n"
      }
     ]
    },
    {
     "title": "Running Threads",
     "type": "bargauge",
     "gridPos": { "h": 2, "w": 4, "x": 0, "y": 94 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "dataset": "DemoDB",
       "rawSql": "SELECT COUNT(*) AS Running_Threads\nFROM sys.dm_exec_requests\nWHERE status = 'running';\n"
      }
     ]
    },
    {
     "title": "Open Files Limit",
     "type": "bargauge",
     "gridPos": { "h": 2, "w": 4, "x": 4, "y": 94 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "dataset": "DemoDB",
       "rawSql": "SELECT \n    COUNT(*) AS OpenFiles\nFROM sys.dm_io_pending_io_requests;\n"
      }
     ]
    }
   ]
  },
  {
   "title": "Buffer and Index Management",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 83 },
   "collapsed": true,
   "panels": [
    {
     "title": "Buffer Pool Hit Rate",
     "type": "bargauge",
     "gridPos": { "h": 10, "w": 4, "x": 0, "y": 156 },
     "fieldConfig": { "defaults": { "unit": "decmbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "dataset": "DemoDB",
       "rawSql": "SELECT \n    CAST(COUNT(*) * 8.0 / 1024 AS DECIMAL(10, 2)) AS 'Buffer Pool Used MB',\n    CAST(SUM(CASE WHEN is_modified = 1 THEN 1 ELSE 0 END) * 8.0 / 1024 AS DECIMAL(10, 2)) AS 'Dirty Buffer MB',\n    CAST(COUNT(*) * 8.0 / 1024 AS DECIMAL(10, 2)) AS 'Buffer Pool Total MB',\n    CAST(SUM(CASE WHEN is_modified = 1 THEN 1 ELSE 0 END) * 8.0 / 1024 AS DECIMAL(10, 2)) AS 'Dirty Buffer Used MB'\nFROM sys.dm_os_buffer_descriptors\nWHERE database_id > 4;\n"
      }
     ]
    },
    {
     "title": "Buffer Pool Usage",
     "type": "barchart",
     "gridPos": { "h": 10, "w": 4, "x": 4, "y": 156 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "dataset": "DemoDB",
       "rawSql": "SELECT \n    (total_physical_memory_kb / 1024) AS 'Total Physical Memory MB',\n    (available_physical_memory_kb / 1024) AS 'Available Physical Memory MB',\n    (total_page_file_kb / 1024) AS 'Total Page File MB',\n    (available_page_file_kb / 1024) AS 'Available Page File MB',\n    (system_memory_state_desc) AS 'System Memory State Description'\nFROM sys.dm_os_sys_memory;\n"
      }
     ]
    },
    {
     "title": "Page Life Expectancy",
     "type": "gauge",
     "gridPos": { "h": 10, "w": 3, "x": 21, "y": 156 },
     "targets": [
      {
       "dataset": "_DBA",
       "rawSql": "SELECT [object_name], [counter_name], [cntr_value] AS PageLifeExpectancy\nFROM sys.dm_os_performance_counters\nWHERE [object_name] LIKE '%Buffer Manager%'\nAND [counter_name] = 'Page life expectancy';\n"
      }
     ]
    }
   ]
  },
  {
   "title": "Database Space Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 84 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Space MB",
     "type": "bargauge",
     "description": "modify the max with the size of your disk associated with the database",
     "gridPos": { "h": 5, "w": 3, "x": 0, "y": 157 },
     "fieldConfig": { "defaults": { "unit": "decmbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "dataset": "DemoDB",
       "rawSql": "SELECT \n    ISNULL(t.NAME, 'Total') AS TableName,\n    ISNULL(s.NAME, '') AS SchemaName,\n    CAST(ROUND(((SUM(a.total_pages) * 8) / 1024.0), 2) AS DECIMAL(18, 2)) AS TotalSpaceMB\nFROM \n    sys.tables t\nINNER JOIN      \n    sys.indexes i ON t.OBJECT_ID = i.object_id\nINNER JOIN \n    sys.partitions p ON i.object_id = p.OBJECT_ID AND i.index_id = p.index_id\nINNER JOIN \n    sys.allocation_units a ON p.partition_id = a.container_id\nINNER JOIN \n    sys.schemas s ON t.schema_id = s.schema_id\nGROUP BY \n    ROLLUP(t.Name, s.Name)\nORDER BY \n    CASE WHEN t.Name IS NULL THEN 1 ELSE 0 END,\n    TotalSpaceMB DESC;\n"
      }
     ]
    },
    {
     "title": "Used Space MB",
     "type": "bargauge",
     "description": "modify the max with the size of your disk associated with the database",
     "gridPos": { "h": 5, "w": 3, "x": 3, "y": 157 },
     "fieldConfig": { "defaults": { "unit": "decmbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "dataset": "DemoDB",
       "rawSql": "SELECT \n    ISNULL(t.NAME, 'Total') AS TableName,\n    ISNULL(s.NAME, '') AS SchemaName,\n    CAST(ROUND(((SUM(a.used_pages) * 8) / 1024.0), 2) AS DECIMAL(18, 2)) AS UsedSpaceMB\nFROM \n    sys.tables t\nINNER JOIN      \n    sys.indexes i ON t.OBJECT_ID = i.object_id\nINNER JOIN \n    sys.partitions p ON i.object_id = p.OBJECT_ID AND i.index_id = p.index_id\nINNER JOIN \n    sys.allocation_units a ON p.partition_id = a.container_id\nINNER JOIN \n    sys.schemas s ON t.schema_id = s.schema_id\nGROUP BY \n    ROLLUP(t.Name, s.Name)\nORDER BY \n    CASE WHEN t.Name IS NULL THEN 1 ELSE 0 END,\n    UsedSpaceMB DESC;\n"
      }
     ]
    },
    {
     "title": "Transaction Log Space Usage",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 18, "x": 6, "y": 157 },
     "fieldConfig": { "defaults": { "unit": "decmbytes" } },
     "targets": [
      { "rawSql": "dbcc sqlperf (logspace)" }
     ]
    },
    {
     "title": "Unused Space MB",
     "type": "bargauge",
     "description": "modify the max with the size of your disk associated with the database",
     "gridPos": { "h": 5, "w": 3, "x": 0, "y": 162 },
     "fieldConfig": { "defaults": { "unit": "decmbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "dataset": "DemoDB",
       "rawSql": "SELECT \n    ISNULL(t.NAME, 'Total') AS TableName,\n    ISNULL(s.NAME, '') AS SchemaName,\n    CAST(ROUND(((SUM(a.total_pages - a.used_pages) * 8) / 1024.0  * 100), 2) AS DECIMAL(18, 2)) AS UnusedSpaceMB\nFROM \n    sys.tables t\nINNER JOIN      \n    sys.indexes i ON t.OBJECT_ID = i.object_id\nINNER JOIN \n    sys.partitions p ON i.object_id = p.OBJECT_ID AND i.index_id = p.index_id\nINNER JOIN \n    sys.allocation_units a ON p.partition_id = a.container_id\nINNER JOIN \n    sys.schemas s ON t.schema_id = s.schema_id\nGROUP BY \n    ROLLUP(t.Name, s.Name)\nORDER BY \n    CASE WHEN t.Name IS NULL THEN 1 ELSE 0 END,\n    UnusedSpaceMB DESC;\n"
      }
     ]
    },
    {
     "title": "Memory Grants Pending",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 3, "x": 3, "y": 162 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "dataset": "_DBA",
       "rawSql": "SELECT COUNT(*) AS MemoryGrantsPending\nFROM sys.dm_exec_query_memory_grants\nWHERE grant_time IS NULL;\n"
      }
     ]
    },
    {
     "title": "Database File Usage",
     "type": "piechart",
     "gridPos": { "h": 7, "w": 4, "x": 6, "y": 165 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "dataset": "_DBA",
       "rawSql": "SELECT name AS FileName,\n       size/128 AS FileSizeMB,\n       physical_name AS PhysicalName\nFROM sys.master_files;\n"
      }
     ]
    },
    {
     "title": "Backup Status",
     "type": "table",
     "gridPos": { "h": 7, "w": 10, "x": 10, "y": 165 },
     "fieldConfig": { "defaults": { "unit": "decmbytes" } },
     "targets": [
      {
       "dataset": "_DBA",
       "rawSql": "SELECT database_name, \n       backup_start_date, \n       backup_finish_date, \n       backup_size / 1024 / 1024 AS BackupSizeMB\nFROM msdb.dbo.backupset\nORDER BY backup_start_date DESC;\n"
      }
     ]
    },
    {
     "title": "Row Count",
     "type": "gauge",
     "gridPos": { "h": 7, "w": 4, "x": 20, "y": 165 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "dataset": "DemoDB",
       "rawSql": "SELECT \n    ISNULL(t.NAME, 'Total') AS TableName,\n    ISNULL(s.NAME, '') AS SchemaName,\n    SUM(p.rows) AS RowCounts\nFROM \n    sys.tables t\nINNER JOIN      \n    sys.indexes i ON t.OBJECT_ID = i.object_id\nINNER JOIN \n    sys.partitions p ON i.object_id = p.OBJECT_ID AND i.index_id = p.index_id\nINNER JOIN \n    sys.schemas s ON t.schema_id = s.schema_id\nGROUP BY \n    ROLLUP(t.Name, s.Name)\nORDER BY \n    CASE WHEN t.Name IS NULL THEN 1 ELSE 0 END,\n    RowCounts DESC;\n"
      }
     ]
    },
    {
     "title": "Table Locks",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 167 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "dataset": "DemoDB",
       "rawSql": "SELECT \n    request_session_id AS 'Session ID',\n    resource_database_id AS 'Database ID',\n    resource_associated_entity_id AS 'Entity ID',\n    request_mode AS LockType,\n    request_status AS Status\nFROM sys.dm_tran_locks;\n"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 172 },
     "fieldConfig": { "defaults": { "unit": "deckbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "dataset": "_DBA",
       "rawSql": "SELECT total_physical_memory_kb, \n       available_physical_memory_kb, \n       total_page_file_kb, \n       available_page_file_kb\nFROM sys.dm_os_sys_memory;\n"
      }
     ]
    },
    {
     "title": "TempDB Disk Monitoring",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 13, "x": 11, "y": 172 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "dataset": "_DBA",
       "rawSql": "SELECT database_id, \n       file_id, \n       io_stall_read_ms AS DiskReadStall, \n       io_stall_write_ms AS DiskWriteStall, \n       num_of_reads, \n       num_of_writes\nFROM sys.dm_io_virtual_file_stats (2, NULL);\n"
      }
     ]
    }
   ]
  }
 ]
}